from coe_file_tools import *

init_header("update suite")
m_update(None, 0, 5)
m_assert(True, 0)
m_update(0, 2, 10)
m_assert(True, 1)
m_update(None, 4, 10)
m_assert(True, 2)
m_update(2, 10, 21)
m_assert(True, 3)
m_update(1, 9, 5)
m_assert(True, 4)
m_update(1, 11, 14)
m_assert(True, 5)
m_lookUp(0, 0)
m_assert(True, 5)
m_lookUp(1, 0)
m_assert(True, 5)
m_lookUp(1, 2)
m_assert(True, 10)
m_lookUp(3, 4)
m_assert(True, 10)
m_lookUp(5, 2)
m_assert(True, 10)
m_lookUp(5, 1)
m_assert(False, 0)
m_delete(1)
m_assert(True, 0)
m_delete(4)
m_assert(True, 0)
m_delete(5)
m_assert(True, 0)
m_lookUp(0, 0)
m_assert(True, 5)
writeCOE()