from esfa_tools import *

value = m_update(None, 0, 5)
assert(value == 0)
value = m_update(0, 2, 10)
assert(value == 1)
value = m_update(None, 4, 10)
assert(value == 2)
value = m_update(2, 10, 21)
assert(value == 3)
value = m_update(1, 9, 5)
assert(value == 4)
value = m_update(1, 11, 14)
assert(value == 5)
value = m_lookUp(0, 0)
assert(value == 5)
value = m_lookUp(1, 0)
assert(value == 5)
value = m_lookUp(1, 2)
assert(value == 10)
value = m_lookUp(3, 4)
assert(value == 10)
value = m_lookUp(5, 2)
assert(value == 10)
value = m_lookUp(5, 1)
assert(value == None)
value = m_delete(1)
assert(value == True)
value = m_delete(4)
assert(value == True)
value = m_delete(5)
assert(value == True)
value = m_lookUp(0, 0)
assert(value == 5)